# Generated by Django 4.2.7 on 2025-04-20 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualclassroom",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="attended_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="virtualclassroom",
            name="chat_messages",
            field=models.ManyToManyField(
                blank=True,
                related_name="classroom_chats",
                to="virtual_classroom.chatmessage",
            ),
        ),
    ]
